### PR TITLE
Utility: Improve `Util_CharDeleteAtIndex` performance

### LINKED ISSUE #6: `Util_CharDeleteAtIndex` is memory inefficient
As the title states, `Util_CharDeleteAtIndex` is very bad with its memory consumption. It works by allocating a duplicate of the entire string in memory, and with larger inputs (a large HTML file, for example), this allocation will simply fail. A new method for this utility needs a proposition and implemented.

### PR DESCRIPTION
**Pull request by MotoLegacy**
Before, this utility function would allocate a new string and iterate through it entirely to fill every entry aside from the index we wanted to ignore. Now, it simply jumps to the index at hand, and just replaces it and subsequence indexes with the character in front of it. This mitigates the need to continually allocate and free memory, instead relying on the same string build and modifying it. Fixes #6.

### CODE REVIEW

File: source/util.c [hunk 1]
```diff
@@ -22,29 +22,20 @@
...
-    tempstr = malloc(sizeof(char) * (len + 1));
-
-    int j = 0;
-    for(int i = 0; i < len; i++) {
-        if (i != index) {
-            tempstr[j] = src[i];
-            j++;
-        }
+    int i;
+    for (i = index; i < len - 1; i++) {
```
Comment (krazynez) [inline source/util.c:35]: Could just replace `i` with `index` entirely.

**Review by krazynez — APPROVED** [review]
Looks good, up to you on the change if it makes more since this way it's fine also.
